# Use root/example as user/password credentials
version: '3'

services:
  dbpostgres:
    image: postgres
    volumes:
      - /home/bruno/dockers/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      # Opens port 5432 on the container
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pgdb
